SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";

CREATE TABLE `visits` (
  `id` int(11) NOT NULL,
  `ip` varchar(60) DEFAULT NULL,
  `date` date DEFAULT NULL,
  `cont` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

ALTER TABLE `visits`
  ADD PRIMARY KEY (`id`);

ALTER TABLE `visits`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
COMMIT;
